//! SEO copy: H1 characteristics = 50–60 words; page description = 150 words per route.

pub const HOME_H1: &str = "Our Palworld Breeding Calculator is a complete toolkit for parent pair testing, reverse target lookups, Pal database browsing, map references, item sources, technology milestones, and capture estimates. It helps you build structured breeding plans instead of random egg cycles, with routes for rare targets like Anubis, Jetragon, and Frostallion in one responsive interface.";

pub const HOME_DESC: &str = "Palworld Breeding Calculator is a free online database and breeding planner for players who want faster routes to rare Pals and fewer wasted eggs. Select any two parents to predict the child, including special combination outcomes and breeding-power fallbacks. The reverse calculator lists every parent pair that can produce your target Pal so you can compare methods side by side. Browse Pal profiles with breeding power, map coordinates, item sources, and technology milestones in one responsive interface. Capture-rate estimates help you farm easier parents before expensive breeding chains. Dedicated pages for popular Pals, parent combos, and step-by-step guides support beginners and endgame breeders alike. With quick-pick grids, theme toggle, and server-rendered pages for search indexing, the tool turns breeding guesswork into repeatable decisions. Whether you are chasing Anubis, Jetragon, or efficient base workers, plan every session with structured data instead of trial and error. Free to use with no login required.";

pub const BREEDING_H1: &str = "This parent combo calculator focuses on forward breeding tests and reverse discovery in Palworld. Pick Parent A and Parent B to predict the child, then use reverse lookup for your target Pal. Special combinations are flagged when they override breeding power rules so you compare methods before long egg cycles.";

pub const BREEDING_DESC: &str = "This Palworld breeding calculator page focuses on parent pair logic and child prediction accuracy. You can test two parents, swap them quickly, and read whether the outcome uses a special combination or breeding power average. The reverse calculator on the same page lists every valid parent route for a chosen child, which is essential when planning legendary targets. Players use this view to compare Anubis routes, Jetragon chains, and mid-game power parents without leaving the browser. The interface loads fast, works on mobile, and links to dedicated Pal and combo pages for deeper research. Whether you are optimizing for rarity, work skills, or combat utility, start here to validate pairs before placing Pals in the Breeding Farm. Use cake management and incubator timing alongside these results for smoother egg cycles. Bookmark this route when you need a reliable online Palworld breeding calculator with reverse finder support and shareable combo links.";

pub const PALS_H1: &str = "The Pals database lists breeding power for the full roster so you compare rarity and plan parents quickly. Filter by name, use quick picks, and send any Pal to the breeding arena without extra typing. Ideal for team planning, capture priority, and stepping-stone parents in long legendary chains across your save.";

pub const PALS_DESC: &str = "Browse every Pal in this database with breeding power rankings that help you understand capture difficulty and breeding chain length. Each Pal links to a dedicated profile page with parent combination tables, related guides, and calculator shortcuts. Use the grid search to find names like Anubis, Lyleen, Jetragon, or Frostallion in seconds. Breeding power is a practical proxy for planning: lower values usually mean rarer targets that require more setup time. Compare neighbors in the list to identify accessible parents you can farm early. The Pals view connects to map data, capture estimates, and combo routes so you do not jump between disconnected tools. Players preparing batch breeding sessions should sort mentally by power tiers before spending resources. This page supports roster review for PvE bases, PvP teams, and work-Pal optimization. Return here whenever you add new captures to your Palbox and need updated planning references for your next egg cycle.";

pub const MAP_H1: &str = "The map reference shows spawn areas and coordinates for key Pals so you spend less time wandering and more time breeding. Chain capture routes with your parent list when preparing legendary projects. Map planning reduces failed trips, saves travel time, and helps pair sphere upgrades with the right biome visits before incubation.";

pub const MAP_DESC: &str = "Map references in this Palworld database highlight where specific Pals appear across the island, including common early-game zones and late-game sanctuaries. Knowing coordinates before you leave base saves hours when farming parents for complex breeding chains. Pair this tab with capture-rate estimates to decide whether a target is worth attempting now or later. Players chasing Anubis, Jetragon, or tower bosses can align travel routes with fast travel points and night-only spawns where applicable. The map panel is designed as a companion to the breeding calculator, not a replacement for exploration, so always verify spawns in-game after major patches. Use it to plan team composition for cold, hot, or neutral biomes depending on Pal elements. When multiple parents are needed, route captures from easiest to hardest power tiers. This reduces inventory clutter and stabilizes egg production at the Breeding Farm. Save this tab when co-op teammates need shared farming routes.";

pub const ITEMS_H1: &str = "The items database explains where materials drop and how crafting resources support breeding, incubation, and base upgrades in Palworld. Review sources before long farming sessions so you are not missing cake ingredients, spheres, or technology components required for smooth egg cycles. This view connects item knowledge to practical breeding progression for mid and late game players.";

pub const ITEMS_DESC: &str = "Items in Palworld gate breeding efficiency more than many players expect. Cake for the Breeding Farm, spheres for captures, and advanced crafting parts for incubators all depend on reliable material routes. This database tab summarizes sources and notes for common drops tied to early and late Pals. Use it when you are preparing a legendary project and need to stock resources in advance. Link item farming with Pal capture plans so one expedition feeds multiple goals. Players optimizing bases should cross-check work-Pal materials here before assigning production lines. The items panel is intentionally concise so you can scan quickly between calculator tests. Combine this data with technology milestones to unlock breeding structures on schedule. When patches add new materials, revisit this section while updating your combo plans. Strong item preparation reduces downtime between eggs and keeps parent Pals fed during long chains. Review this tab before every legendary attempt to avoid stalled progress.";

pub const TECH_H1: &str = "The technology milestones panel tracks unlock levels for breeding farms, incubators, spheres, and production tools that affect how fast you can run Palworld egg cycles. Align tech progression with your capture plan so structures exist before you import high-value parents. This prevents bottlenecks where combos are ready but infrastructure lags behind your roster goals.";

pub const TECH_DESC: &str = "Technology unlocks shape the pace of every breeding project in Palworld. Early points deliver Pal Spheres and basic base tools, while mid-level unlocks introduce the Egg Incubator and Breeding Farm that make systematic combo testing possible. Later tiers improve crafting, storage, and combat gear needed for legendary captures. This guide tab lists milestone levels and costs so you can plan point spending without guesswork. Players rushing a Jetragon or Anubis chain should verify breeding structures are online before farming parents. Production lines for cake and materials also depend on tech depth, so coordinate with the items database. If co-op teammates share progress, compare unlock timing to avoid duplicated research. Post-update planning should revisit this tab because balance changes can shift costs or prerequisites. Use milestones as checkpoints: capture parents only after incubation capacity matches your target egg count. Strong tech discipline shortens total project time more than random pair testing alone.";

pub const CAPTURE_H1: &str = "Capture-rate estimates use breeding power as a practical difficulty guide so you can farm easier parents before expensive legendary chains in Palworld. Compare your target with suggested alternatives, then send promising Pals to the calculator for pair validation. This view helps beginners avoid frustration and helps veterans optimize setup time before multi-day breeding projects.";

pub const CAPTURE_DESC: &str = "Capture planning is half of successful breeding in Palworld because unreachable parents stall entire combo trees. This page translates breeding power into estimated catch difficulty and lists easier targets that may work as stepping stones. Use the data to decide when to upgrade spheres, adjust team levels, or wait for better gear. Legendary projects often fail when players skip capture prep and jump straight to rare children. Pair these estimates with map locations to build same-day routes. The capture tab links back to reverse calculator workflows so you can test whether alternative parents produce the same child with less farming time. Update your plan after each successful capture because new parents unlock fresh pair options. Night-only, alpha, and dungeon spawns still require in-game verification, but power tiers provide a reliable starting filter. Serious breeders review this page before every long session and update targets after each successful capture.";

pub const KEYWORD_BREED_H1: &str = "This online Palworld breeding calculator route is optimized for players searching for a browser-based combo tool with instant parent tests and reverse combination lists. No install is required: open the page, pick parents, and read child outcomes plus method type in seconds. It mirrors the main calculator experience while targeting breeding calculator keyword searches directly.";

pub const KEYWORD_BREED_DESC: &str = "Search intent for an online Palworld breeding calculator usually means speed, accuracy, and reverse lookup in one place. This route delivers exactly that with server-rendered SEO pages, structured data, and mobile-friendly controls. Test Parent A and Parent B to see predicted children, including special combinations when fixed pairs override power averages. Switch to reverse mode to list every route for a target like Anubis or Jetragon before you commit resources. The database includes a broad Pal roster, combo pages, and guides for legendary breeding. Players comparing tools should note transparent method labels and links to deeper Pal profiles. Use quick pick grids to reduce typing and theme toggle for comfortable sessions. This page is ideal to bookmark on phone or desktop when you need fast answers between gameplay sessions. It stays free with no login, supports indexing for search engines, and connects to capture and map tabs for full planning.";

pub const KEYWORD_COMBOS_H1: &str = "The Palworld breeding combinations page helps you explore parent pairing options, compare special outcomes against power-average fallbacks, and jump into dedicated combo URLs for documentation. It is built for players who think in pairs first and want method clarity before placing Pals in the Breeding Farm for long egg cycles.";

pub const KEYWORD_COMBOS_DESC: &str = "Breeding combinations are the core language of Palworld endgame planning. This route explains how special pairs differ from standard power-average predictions and why both matter when farming legendaries. Use the calculator to validate pairs, then open combo pages for shareable URLs you can reference later. Combination tables on Pal profiles list multiple routes for the same child so you can choose easier parents. Understanding method labels prevents false expectations when eggs hatch. Players building guides or Discord advice can link combo pages directly instead of screenshots. The combinations view also connects to capture and technology planning so materials and structures keep pace with your pair list. After patches, re-test favorite pairs because new Pals shift viable routes. Whether you are chasing combat, flying mounts, or work specialists, start from combinations and narrow to the cheapest valid parents. This page is your hub for systematic pair exploration and long-term roster planning.";

pub const KEYWORD_CAPTURE_H1: &str = "This capture rate calculator pairs difficulty estimates with easier parent suggestions so you shorten breeding setup before advanced chains. Use it when legendary targets feel out of reach and you need stepping-stone Pals that still satisfy reverse calculator outcomes for your end goal in Palworld with fewer wasted capture attempts.";

pub const KEYWORD_CAPTURE_DESC: &str = "Capture rate planning deserves its own route because breeding math is useless if parents never enter your Palbox. This calculator page estimates difficulty using breeding power tiers and highlights alternative targets that may reduce grind. Combine results with map references to build efficient same-day routes. Players often underestimate sphere quality, status effects, and level gaps; this page encourages preparation before egg investment. Link capture decisions to reverse lookup so you know whether substitutes exist for expensive parents. The capture calculator complements combo pages and Pal profiles for full-project planning. Use it at the start of every legendary attempt to avoid stalled incubators. Update strategy after each capture because new parents change available pairs instantly. Long-term breeders revisit this tab when co-op friends join and roster power spikes. Treat capture estimates as planning guidance, then confirm in-game because event spawns and mods can shift reality. Use it when mentoring new players on safer legendary projects.";

pub const CHAIN_H1: &str = "The chain breeding finder shows the shortest Palworld egg route from a Pal you own to any target. Pick owned and goal Pals, then read each step with parent pairs, methods, and combo links. Uses the same live data as the main calculator so special pairs and power averages stay accurate.";

pub const CHAIN_DESC: &str = "Palworld chain breeding is how players turn common captures into legendaries without guessing every intermediate egg. This chain breeder searches backward from your target Pal, picks easier parent pairs at each step, and stops when the only Pals left to obtain are ones you already own. Each step links to our combo pages and reverse calculator so you can verify methods before spending cake in the Breeding Farm. Use it when planning Jetragon, Anubis, Frostallion, or any rare target from a starter like Lamball or Cattiva. Chains are limited to ten eggs for performance but cover most practical routes. Combine this tool with Pal profile pages, how-to-breed guides, and capture estimates for a full project plan. Mobile-friendly and free with no login, it helps beginners and veterans reduce wasted incubation time. Bookmark this page when restructuring your roster or preparing a co-op breeding session and share chain URLs with teammates.";

/// Sitewide footer: internal links for crawl paths and user navigation (injected on all page types).
pub const SITE_FOOTER_HTML: &str = r#"<footer class="site-footer" role="contentinfo">
  <div class="site-footer-inner">
    <div class="site-footer-col">
      <p class="site-footer-title">Palworld Breeding Calculator</p>
      <p class="site-footer-muted">Free combo tool, reverse lookup, chain paths, and Pal database.</p>
    </div>
    <nav class="site-footer-col" aria-label="Tools">
      <p class="site-footer-heading">Tools</p>
      <ul>
        <li><a href="/palworld-breeding-calculator">Breeding Calculator</a></li>
        <li><a href="/palworld-breeding-combinations">Breeding Combinations</a></li>
        <li><a href="/palworld-chain-breeding">Chain Breeding</a></li>
        <li><a href="/palworld-capture-rate-calculator">Capture Rate</a></li>
        <li><a href="/pals">Pals Database</a></li>
        <li><a href="/map">Map Locations</a></li>
      </ul>
    </nav>
    <nav class="site-footer-col" aria-label="Guides">
      <p class="site-footer-heading">Guides</p>
      <ul>
        <li><a href="/how-to-breed/anubis">How to Breed Anubis</a></li>
        <li><a href="/fastest-anubis-breed">Fastest Anubis Breed</a></li>
        <li><a href="/legendary-breeding">Legendary Breeding</a></li>
        <li><a href="/guides/best-breeding-combos">Best Breeding Combos</a></li>
        <li><a href="/guides/breeding-not-working">Breeding Not Working</a></li>
        <li><a href="/egg-incubation-guide">Egg Incubation</a></li>
      </ul>
    </nav>
    <nav class="site-footer-col" aria-label="Popular Pals">
      <p class="site-footer-heading">Popular Pals</p>
      <ul>
        <li><a href="/pal/anubis">Anubis</a></li>
        <li><a href="/pal/jetragon">Jetragon</a></li>
        <li><a href="/pal/frostallion">Frostallion</a></li>
        <li><a href="/pal/lyleen">Lyleen</a></li>
        <li><a href="/pal-pages">All Pal Pages</a></li>
        <li><a href="/combo-pages">Combo Pages</a></li>
      </ul>
    </nav>
  </div>
  <p class="site-footer-copy">Palworld Breeding Calculator — unofficial fan tool. Not affiliated with Pocketpair.</p>
</footer>"#;

/// Guide page meta descriptions (~150 words) for Search Console / SERP snippets.
pub const GUIDE_HOW_TO_BREED_ANUBIS: &str = "Learn how to breed Anubis in Palworld with a clear parent-path strategy, breeding power context, and reverse calculator workflows that cut wasted eggs. This guide explains unlocking the Breeding Farm and Egg Incubator, stocking cake, and using reverse lookup to list every valid Anubis parent pair including special combinations. Compare capture difficulty before farming, then prioritize easier parents so mid-game handiwork and combat goals arrive faster. Cross-link to the Anubis Pal page, combo hub, and chain breeding tool when you need multi-step routes from Lamball or Cattiva. Mobile-friendly steps cover incubation loops, method labels, and why gender does not change predicted children in standard breeding math. Use this page with our free Palworld breeding calculator to validate pairs before you commit resources. Ideal for beginners finishing first Anubis runs and veterans optimizing cake and incubator capacity. Bookmark for co-op teams sharing the same breeding project.";

pub const GUIDE_BEST_COMBOS: &str = "Explore the best Palworld breeding combo strategy with practical rules for ranking parent pairs, special combinations, and power-average fallbacks before long egg cycles. This guide shows how to use reverse lookup for targets like Anubis, Jetragon, and Lyleen, then compare method labels so you do not misread fixed pairs versus breeding power outcomes. Learn when capture planning and map routes matter more than rare parents, and how chain breeding shortens legendary projects from Pals you already own. Pair combo decisions with technology milestones, cake supply, and incubator capacity for smoother sessions. Dedicated combo pages and Pal profiles give shareable URLs for Discord or co-op notes. Whether you optimize for work skills, combat, or flying mounts, start with systematic pair evaluation instead of random breeding. Free calculator links keep every recommendation testable in one browser tab. Update favorite routes after patches when new Pals shift viable combinations.";

pub const GUIDE_CAPTURE_RATE: &str = "Understand Palworld capture rate planning with breeding-power difficulty estimates that help you farm easier parents before expensive legendary breeding chains. This guide explains how our capture calculator turns power tiers into practical catch difficulty, then walks a workflow: reverse-list target pairs, sort by easier parents, upgrade spheres, and use map coordinates for one efficient trip. Learn when to delay ultra-rare captures and breed stepping-stone children instead so incubators stay busy. Combine capture prep with legendary breeding guides for Jetragon, Frostallion, and Necromus, plus troubleshooting when eggs stall after successful catches. Estimates are planning guidance—confirm in-game after patches—but power tiers remain a reliable filter for beginners and veterans. Use this page before every multi-day breeding project to reduce failed expeditions and wasted cake. Links to the breeding calculator and Pal database keep capture decisions tied to real combo outcomes.";

pub const GUIDE_FASTEST_ANUBIS: &str = "Find the fastest Anubis breed routes in Palworld by sorting parent pairs for speed: fewest captures, fewest eggs, and earliest handiwork payoff. This page walks reverse lookup for Anubis, capture-estimate sorting, special combination priority, and chain-tool checks from common starters like Lamball. Open the Anubis combo hub for bookmarkable pair URLs, then verify methods in our free breeding calculator before placing parents in the Breeding Farm. Compare special pairs against power-average alternatives so you do not waste cake on slower routes. Cross-links cover the full how-to-breed Anubis guide and Anubis versus Lyleen role comparison when choosing mid-game priorities. Mobile-friendly steps help co-op teams share the same speed path. Ideal when you need Anubis quickly for base crafting without starting a legendary-length project. Re-test favorite pairs after updates because new Pals can unlock shorter chains.";

pub const GUIDE_LEGENDARY: &str = "Plan legendary Pal breeding in Palworld with a phased workflow for Jetragon, Frostallion, Necromus, Paladius, and other rare targets that rarely hatch from one lucky egg. This guide covers Breeding Farm and incubator infrastructure, cake production, stepping-stone mid-tier parents, and chain or reverse planning from Pals you already own. Use capture estimates to avoid wasted legendary trips, then verify every step on Pal pages, how-to-breed hubs, and combo URLs before spending resources. Popular routes for flying mounts, ice legendaries, and duo bosses are linked with calculator shortcuts so methods stay transparent. Track multi-day projects with bookmarks and notes instead of re-discovering pairs each session. Combine this legendary breeding guide with egg incubation tips and technology milestones so structures keep pace with your chain. Free tools, no login, mobile-ready planning for serious endgame breeders and co-op teams sharing roster goals.";

pub const GUIDE_EARLY_GAME: &str = "Discover the best early game Palworld breeding combos using easy-to-catch parents like Lamball, Cattiva, Chikipi, Foxparks, and Pengullet for fast eggs and useful workers. This guide prioritizes practical base progression over legendary rushes, with calculator checks for special combinations and low breeding-power distance pairs. Learn what to avoid early—Hyper Sphere legendaries, cake shortages, and incubator bottlenecks—while unlocking Breeding Farm technology on schedule. Pair starter combos with capture planning so one farming loop feeds multiple goals. Test pairs in our free breeding calculator, then open Pal pages for Lamball-tier parents before expanding to Anubis projects. Ideal for the first ten hours of a save when cake and spheres are limited. Mobile-friendly tips help new players build habits that scale into mid-game chains without restarting bad strategies. Bookmark this early breeding guide when mentoring friends on safer first combos.";

pub const GUIDE_EGG_INCUBATION: &str = "Master Palworld egg incubation with unlock order, cake habits, and incubator capacity tips that turn valid parent pairs into hatched children without idle Breeding Farms. This guide covers Egg Incubator and Breeding Farm technology milestones, collecting eggs quickly so parents cycle again, and matching incubator settings when the game requires warmth types. Link incubation to combo validation in our breeding calculator and combo pages so you never hatch undocumented pairs. Use multiple incubators for legendary chains and read troubleshooting when hatches stall despite assigned parents. Combine this egg incubation guide with chain breeding so every intermediate egg is planned before cake is spent. Practical for solo and co-op bases that need predictable hatch throughput. Free references stay updated alongside the Pal database and capture tools. Return here whenever incubation becomes the bottleneck between reverse lookup results and finished roster upgrades.";

pub const GUIDE_MINING: &str = "Find mining-focused Pal breeding routes in Palworld for ore bases, Digtoise-tier workers, and work suitability planning tied to real calculator math. This guide explains defining a mining target, opening its Pal page, and reverse-looking parent pairs while preferring easier capture routes first. Breeding power predicts species—not Mining Level passives—so expect multiple hatches when rolling work skills. Pair breeding with items database farming and capture estimates so materials and parents arrive together. Compare support roles like Anubis versus Lyleen when splitting combat and production duties across your base. Use the free breeding calculator to verify special combinations before long egg loops. Built for players optimizing ore throughput without guessing pairs. Mobile-friendly links keep mining projects organized from early captures through late work-Pal upgrades after patches shift the roster.";

pub const GUIDE_FLYING_MOUNT: &str = "Speed up flying mount breeding in Palworld with Jetragon-focused paths, parent combo checks, and capture planning that beats lucky single-egg attempts. This guide outlines reverse-listing Jetragon pairs, spotting special combinations, farming easier high-power parents, and running the chain breeder from Pals you already own. Capture Jetragon itself is endgame—many players breed stepping stones first using legendary breeding and capture rate guides. Compare alternative flying-adjacent Pals on the Pal database when Jetragon is weeks away on your save. Verify every method in our free calculator and how-to-breed Jetragon hub before committing cake. Co-op teams can share combo URLs instead of screenshots. Practical, mobile-ready planning for mount projects that respect capture difficulty and incubator capacity. Revisit after updates when new mounts or parents appear in the breeding table.";

pub const GUIDE_ANUBIS_VS_LYLEEN: &str = "Compare Anubis versus Lyleen in Palworld for breeding power, roster roles, and which target to chase first with calculator-backed parent difficulty. Anubis delivers mid-game handiwork and combat utility with more accessible routes, while Lyleen is a rarer late support breeder with longer chains. This comparison links how-to-breed Anubis, fastest Anubis routes, and the Lyleen Pal page so you can reverse-lookup both targets side by side. Shared tips cover cake stock, multiple incubators, and preferring special combinations over random power-average tests. Most players should finish Anubis before Lyleen unless endgame production passives are the priority. Use best-combos strategy pages to rank methods consistently across both projects. Free tools, clear role guidance, and mobile-friendly links for solo or co-op planning. Update decisions after patches when breeding power or special pairs change.";

pub const GUIDE_BREEDING_NOT_WORKING: &str = "Fix Palworld breeding when eggs do not appear, cake runs out, or parent pairs fail with a step-by-step checklist before you waste resources. Confirm the Breeding Farm is built and powered, both parent slots filled, and cake stocked in the feed box. Verify the pair in our free breeding calculator so invalid combinations are not blamed on game bugs. Collect eggs promptly, ensure incubator space exists, and heal starving or sick parents that can stall loops. Still stuck? Compare routes on how-to-breed hubs and Pal pages, then re-test special versus power-average methods. This troubleshooting guide pairs with egg incubation and capture planning so infrastructure and parents stay aligned. Ideal for beginners and veterans after patches who need a fast recovery path. Mobile-friendly steps keep base checks quick between gameplay sessions without leaving the calculator ecosystem.";

